name: lead_lyon
channels:
  - defaults
dependencies:
  - numpy=1.20.2
  - scipy=1.6.2
  - pandas=1.2.5
  - tqdm=4.61.1
  - jupyter=1.0.0
  - nbconvert=6.1.0
  - matplotlib=3.3.4
  - pip=21.1.3
  - python=3.8.2
  - networkx=2.5.1
  - scikit-learn=0.24.2
  - pip:
    - pyrosm==0.6.0
    - geopandas==0.9.0
